/**:
  ros__parameters:
    resample:
      ds_resample: 0.1
      num_resample: 1
      delta_yaw_threshold: 0.785

    latacc:
      enable_constant_velocity_while_turning: false
      constant_velocity_dist_threshold: 2.0

    forward:
      max_acc: 1.0
      min_acc: -1.0
      max_jerk: 0.3
      min_jerk: -0.3
      kp: 0.3

    backward:
      start_jerk: -0.1
      min_jerk_mild_stop: -0.3
      min_jerk: -1.5
      min_acc_mild_stop: -1.0
      min_acc: -2.5
      span_jerk: -0.01
