/**:
  ros__parameters:
    min_stop_distance: 5.0
    stop_time: 2.0
    hysteresis_buffer_distance: 2.0
    backward_path_length: 5.0
    forward_path_length: 300.0
    max_accel: -5.0
    lane_change_prepare_duration: 4.0
    lane_changing_duration: 8.0
    backward_length_buffer_for_end_of_lane: 5.0
    lane_change_finish_judge_buffer: 3.0
    minimum_lane_change_length: 12.0
    minimum_lane_change_velocity: 5.6
    prediction_duration: 8.0
    prediction_time_resolution: 0.5
    drivable_area_resolution: 0.1
    drivable_area_width: 100.0
    drivable_area_height: 50.0
    static_obstacle_velocity_thresh: 1.5
    maximum_deceleration: 1.0
    refine_goal_search_radius_range: 7.5
