/**:
  ros__parameters:
    perception:
      type: diagnostic_aggregator/AnalyzerGroup
      path: perception
      analyzers:
        node_alive_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: node_alive_monitoring
          analyzers:
            topic_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: topic_status
              contains: [": perception_topic_status"]
              timeout: 1.0
