/**:
  ros__parameters:
    launch_stop_line: true
    launch_crosswalk: true
    launch_traffic_light: true
    launch_intersection: true
    launch_blind_spot: true
    launch_detection_area: true
    launch_virtual_traffic_light: true
    launch_occlusion_spot: true
    launch_no_stopping_area: true
    launch_run_out: false
    forward_path_length: 1000.0
    backward_path_length: 5.0
    max_accel: -2.8
    max_jerk: -5.0
    system_delay: 0.5
    delay_response_time: 0.5
    is_publish_debug_path: false # publish all debug path with lane id in each module
