/**:
  ros__parameters:
    pull_out:
      th_arrived_distance: 1.0
      th_stopped_velocity: 0.01
      th_stopped_time: 1.0
      collision_check_margin: 1.0
      pull_out_finish_judge_buffer: 1.0
      # shift pull out
      enable_shift_pull_out: true
      shift_pull_out_velocity: 2.0
      pull_out_sampling_num: 4
      before_pull_out_straight_distance: 0.0
      minimum_shift_pull_out_distance: 20.0
      maximum_lateral_jerk: 2.0
      minimum_lateral_jerk: 0.5
      deceleration_interval: 15.0
      # geometric pull out
      enable_geometric_pull_out: true
      geometric_pull_out_velocity: 1.0
      arc_path_interval: 1.0
      lane_departure_margin: 0.2
      backward_velocity: -1.0
      pull_out_max_steer_angle: 0.26  # 15deg
      # search start pose backward
      enable_back: true
      search_priority: "efficient_path"  # "efficient_path" or "short_back_distance"
      max_back_distance: 15.0
      backward_search_resolution: 2.0
      backward_path_update_duration: 3.0
