/**:
  ros__parameters:
    backward_path_length: 5.0
    forward_path_length: 300.0
    backward_length_buffer_for_end_of_lane: 5.0
    backward_length_buffer_for_end_of_pull_over: 5.0
    backward_length_buffer_for_end_of_pull_out: 5.0
    minimum_lane_change_length: 12.0
    minimum_pull_over_length: 16.0
    drivable_area_resolution: 0.1
    drivable_lane_forward_length: 50.0
    drivable_lane_backward_length:  5.0
    drivable_lane_margin: 3.0
    drivable_area_margin: 6.0
    refine_goal_search_radius_range: 7.5
    intersection_search_distance: 30.0
    path_interval: 2.0
